#??
server:
  port: 8181
  servlet:
    context-path: /community

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niuke?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root

    password: 123456
  # ThymeleafProperties
  thymeleaf:
    cache: true

  # MailProperties
  mail:
    host: smtp.qq.com
    port: 465
    default-encoding: UTF-8
    username: 3217778348@qq.com
    password: fzqnycpmfqdzdddd
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: ture
#            文件
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true

#redis
  redis:
    database: 5
    host: localhost
    port: 6379

# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yy.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# logger
logging-level: com.yy.community=debug

#commnunity
community:
  path:
    domain: https://localhost:8181
    upload: E:/JavaWeb/Example/牛客/community/data/upload

