#??
server:
  port: 8181
  servlet:
    context-path: /

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niuke?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
# ThymeleafProperties
  thymeleaf:
    cache: false
# MailProperties
  mail:
    host: smtp.qq.com
    port: 465
    default-encoding: UTF-8
    username: 3217778348@qq.com
    password: fzqnycpmfqdzdddd
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: ture



# MybatisProperties

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yy.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
# logger

logging-level: com.yy.community=debug

#commnunity
community:
  path:
    domain: https://localhost:8181
