#??
server:
  port: 8181
  servlet:
  tomcat:
    max-http-header-size: 8192

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niuke?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # ThymeleafProperties
  thymeleaf:
    cache: true

  # MailProperties
  mail:
    host: smtp.qq.com
    port: 465
    default-encoding: UTF-8
    username: 3217778348@qq.com
    password: fzqnycpmfqdzdddd
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: ture
  #            文件
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true

  #redis
  redis:
    database: 5
    host: localhost
    port: 6379

  #    kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

  #      es
  data:
    elasticsearch:
      cluster-name: yy
      cluster-nodes: 127.0.0.1:9300


  #      TaskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

        # QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: driverDelegateClass
          isClustered: true
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5

# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yy.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# logger
logging-level: com.yy.community=debug

#commnunity
community:
  path:
    domain: https://localhost:8181
    upload: E:/JavaWeb/Example/牛客/community/data/upload

#    wk
wk:
  image:
    command: E:/JavaWeb/wkhtmltox/wkhtmltopdf/bin/wkhtmltoimage
    storage: E:/JavaWeb/wkhtmltox/wkhtmltopdf/data/wk-images

#   caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180


#    actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info,caches
